### ISSUE TITLE
python brute force attack code

### ISSUE THREAD

**Issue by Shizyxd** [pyth/3d_models#1]
sifre = '19372''
flag = False
rakamlar = ''0123456789''

for basamak0 in rakamlar :
   for basamak1 in rakamlar :
     for basamak2 in rakamlar :
        for basamak3 in rakamlar :
            for basamak4 in rakamlar :
                 deneme = (basamak1+basamak2+basamak3+basamak4)
                print(deneme)
                 if deneme == sifre:
                     print(Parolanız: +deneme)
                    flag  = True
                    break 
            if flag == True:
                break     
       if flag == True:
                break  
    if flag == True:
                break  
if flag == True:
                break

**Comment by pyth** [comment]
Sorry, I don't know what you mean by this.
What does brute forcing a five digit password have to do with my 3d models?

**Comment by pyth** [comment]
Doesn't seem to be related to this repository.

**Comment by pyth** [comment]
Doesn't seem to be related to this repository.
